### ISSUE TITLE
special case ppx_<pkg>?

### ISSUE THREAD

**Issue by avsm** [diml/topkg-jbuilder#1]
The `auto` mode doesnt work in mirage/ocaml-cstruct since it also includes a ppx_cstruct package. Should the auto mode special case ppx_* to match it against the default name of the package?

**Comment by ghost** [comment]
But then what do you do when there is a single ppx_foo package? Why not name the package cstruct-ppx? The latter seems better to me, especially the various cstruct packages will be grouped together in package listings. That's what js_of_ocaml does.

In the end this rule would be a bit ad-hoc and would only save one line in the pkg.ml file, so I don't think it's worth it.

**Comment by rgrinberg** [comment]
I think changing it to cstruct-ppx was done a swell. I only chose ppx_cstruct becuse that was the original findlib name chosen by let-def when he ported the cstruct.ppx to omp.

**Comment by avsm** [comment]
> In the end this rule would be a bit ad-hoc and would only save one line in the pkg.ml file, so I don't think it's worth it.

Agreed -- closing this.

@rgrinberg the convention for ppx names seems to be ppx_* - it does make them easier to discover...
