### ISSUE TITLE
topkg not building documentation

### ISSUE THREAD

**Issue by mmottl** [diml/topkg-jbuilder#7]
I have recently started running into problems building API documentation for packages built with `topkg-jbuilder`.  Could you please check the following issue that was submitted to the `topkg` maintainer and let me know whether this is an issue that can be solved within `topkg-jbuilder`?

  https://github.com/dbuenzli/topkg/issues/118

**Comment by samoht** [comment]
It is supposed to work out-of-the box if you pin the dev version of topkg-jbuilder and it will also work without having to provide a `doc/` directory once https://github.com/dbuenzli/topkg/pull/114 is merged.

**Comment by samoht** [comment]
Can you try it and report if it works for you? If that's the case I'll cut a new release.

**Comment by mmottl** [comment]
Thanks a lot, this works for me!

**Comment by samoht** [comment]
0.2 has been released
